#!/usr/bin/env bash

#
#Copyright © 2020 Christian Niehoff <mail@christian-niehoff.com>
#
#Licensed under the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.
#You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
#Unless required by applicable law or agreed to in writing, software
#distributed under the License is distributed on an "AS IS" BASIS,
#WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#See the License for the specific language governing permissions and
#limitations under the License.

if [ "$1" == "--help" ]; then
  echo "When you want to access kubernetes resources inside a cluster, you either:"
  echo "a) need to expose them via e.g. an Ingress"
  echo "b) run kube-proxy"
  echo "c) forward ports between your local machine and services running inside the cluster."
  echo
  echo "Via kubectl bash you can run plain curl command without exposing any services or forwarding ports."
  echo
  echo "It works by running a pod with radial/busyboxplus:curl image inside the cluster."
  echo
  echo "Usage:"
  echo "  kubectl bash"
  exit 0
fi

kubectl get pod curl > /dev/null 2>&1
rc=$?

if [ $rc -ne 0 ]; then
  echo "Not running, creating a new one"
  kubectl run curl --stdin --tty --generator=run-pod/v1 --image=rekzi/busybox-curl:7.65.3
else
  echo "Attaching to existing pod..."
  POD=$(kubectl get pods --selector=run=curl -o jsonpath='{.items[*].metadata.name}')
  kubectl attach "${POD}" --container curl --stdin --tty
fi
